### ISSUE TITLE
[♻️ refactor] 소셜 로그인 > 토큰 생성 메서드 리팩토링 및 파라미터 간소화 작업

### ISSUE THREAD

**Issue by jsoonworld** [teamterning/Terning-Server#104]
---
labels: [소셜로그인]
---

## ⚙️ ISSUE
- 통합된 토큰 생성 로직을 각각의 메서드로 분리합니다.
- 파라미터를 DTO로 통합하여 파라미터 간소화 작업을 진행합니다.
- 중복된 코드가 최소화될 수 있도록 리팩토링합니다.

## 📄 To-Do
- [ ] 토큰 생성 로직에서 중복된 코드를 분석하여 공통 메서드로 추출
- [ ] getToken 및 getAccessToken 메서드를 각각의 기능에 맞게 분리
- [ ] 파라미터를 DTO로 변환하여 코드 간소화
