### ISSUE TITLE
[ ✨ feat ] 소셜 로그인 기능 개발 

### ISSUE THREAD

**Issue by jsoonworld** [teamterning/Terning-Server#11]
---
labels: [소셜로그인]
---

## ⚙️ ISSUE
- 로셜 로그인 기능을 구현합니다.

## 📄 To-Do
- [ ] Service (apple, Kakao) 구현
- [ ] Controller 구현
- [ ] jwt 기능 개발
- [ ] message 설정
- [ ] Token 로직 구현

**Comment by jsoonworld** [comment]
새로운 환경에서 작업을 위해 이슈를 닫습니다.
