### ISSUE TITLE
[♻️ refactor] 소셜 로그인 > `AuthServiceImpl`의 private 메서드 네이밍 가시성 개선 및 @Transactional 적용

### ISSUE THREAD

**Issue by jsoonworld** [teamterning/Terning-Server#121]
---
labels: [소셜로그인]
---

## ⚙️ ISSUE
- 파라미터로만 구분되던 메서드들을 네이밍을 통해 명확히 구분할 수 있도록 개선합니다.
- `private` 메서드에도 `@Transactional`을 적용합니다.

## 📄 To-Do
- [ ] `AuthServiceImpl`의 `private` 메서드 네이밍 규칙 점검
- [ ] 파라미터로만 구분되던 메서드들에 대해 명확한 네이밍 적용
- [ ] `private` 메서드에 `@Transactional` 어노테이션 적용
