### ISSUE TITLE
[✨ feat] 마이페이지 > 프로필 정보 이미지 전달방식 변경 & 마이페이지 > 프로필 수정 기능 추가

### ISSUE THREAD

**Issue by junggyo1020** [teamterning/Terning-Server#123]
## ⚙️ ISSUE
- 온보딩 > 회원가입의 profileImage를 int 타입에서 String 타입으로 전달 받도록 변경합니다.
- 마이페이지 > 프로필 정보 이미지 전달방식을 int에서 String타입으로 변경합니다.
(6개의 String Enum 타입 중 하나: basic, lucky, smart, glass, calender, passion)
- 마이페이지 > 프로필 수정 기능을 추가합니다.

## 📄 To-Do
- [x] API 명세서 수정(회원가입, 프로필 정보, 프로필 정보 수정)
- [x] 회원가입 이미지 전달방식 수정
- [x] 마이페이지 > 프로필 정보 이미지 전달방식 수정
- [x] 마이페이지 > 프로필 수정 기능 추가
