### ISSUE TITLE
[♻️ refactor] 공고 상세 정보 및 검색 결과 화면 response body 수정

### ISSUE THREAD

**Issue by JungYoonShin** [teamterning/Terning-Server#129]
---
labels: [공고 상세], [탐색]
---

## ⚙️ ISSUE
- 공고 상세 정보 및 검색 결과 화면 response body 수정

## 📄 To-Do
- [x] 공고 상세 response dto ->  color 필드 추가
- [x] scrapId 대신 isScrapped(boolean)필드로 변경
- [x] 공고 상세 response dto -> startDate(근무시작일) 필드명을 startYearMonth로 변경 (다른 API와의 통일성 위해)
- [x] 검색 결과화면 response dto -> totalCount 필드 추가
