### ISSUE TITLE
[♻️ refactor] ScrapRepository 호출로 인한 N+1 문제 및 성능 저하 개선

### ISSUE THREAD

**Issue by jsoonworld** [teamterning/Terning-Server#175]
---
labels: [홈화면],
---

## ⚙️ ISSUE
- `announcements`의 각 항목에 대해 `ScrapRepository`를 통한 데이터베이스 호출이 반복적으로 발생하여 N+1 문제가 발생.
- `existsByInternshipAnnouncementIdAndUserId`와 `findColorByInternshipAnnouncementIdAndUserId`를 각각 호출하면서 추가적인 쿼리가 발생.
- Stream 내부에서 데이터베이스 호출과 비즈니스 로직이 혼재되어 가독성과 유지보수성이 저하됨.

## 📄 To-Do
- [ ] N+1 문제를 해결하기 위해 `ScrapRepository` 호출을 최적화할 방법 모색.
- [ ] `boolean` 값과 `color` 값을 한 번의 호출로 가져오도록 쿼리 개선.
- [ ] 데이터베이스 호출과 비즈니스 로직을 분리하여 코드 가독성과 유지보수성을 향상.
