### ISSUE TITLE
[♻️ refactor] N+1 문제 해결 및 HomeServiceImpl 성능 개선

### ISSUE THREAD

**Issue by junggyo1020** [teamterning/Terning-Server#177]
### 📦 HomeServiceImpl
- 현재 코드는 scrapRepository를 각 InternshipAnnouncement마다 호출함으로써 데이터베이스 접근이 비효율적으로 이루어지고 있다. (N+1 문제 발생)

### ✅ 개선 하고자 하는 내용
- Scrap 정보를 한 번에 조회 하도록 변경 (QueryDSL Tuple 활용)
- Enum Color의 내부 메서드를 활용해서 색상값을 불러오도록 수정
- 불필요한 메서드를 제거하고, isScrapped 로직을 좀 더 단순하게 수정

###  🚀 기대 효과
- N+1 문제 해결
- 성능 개선 및 가독성 향상
- 코드의 유지보수성 증가

## 📄 To-Do
- [x] Scrap 정보를 한 번에 조회 하도록 변경 (QueryDSL Tuple 활용)
- [x] Enum Color의 내부 메서드를 활용해서 색상값을 불러오도록 수정
- [x] 불필요한 메서드를 제거하고, isScrapped 로직을 좀 더 단순하게 수정
- [x] 성능 테스트 진행
