### ISSUE TITLE
[✅ chore] 예외처리 필드 및 enum 수정

### ISSUE THREAD

**Issue by JungYoonShin** [teamterning/Terning-Server#20]
---
labels: [예외처리], [enum]
---

## ⚙️ ISSUE
7/9 클라 - 서버 회의 후 나온 수정사항들 반영

## 📄 To-Do
- 예외처리 필드 수정
  - [x] 성공시 응답: status, message, result
  - [x] 수정시 응답: status, message
- enum 수정
  - [x] 클라와 주고 받는 모든 인덱스 값은 0부터 시작하도록 수정
