### ISSUE TITLE
[✅ chore] 공통 에러처리 및 응답 초기 설정 세팅

### ISSUE THREAD

**Issue by jsoonworld** [teamterning/Terning-Server#3]
---
labels: [chore], [setting]
---

## ⚙️ ISSUE
- 공통 에러처리 및 응답 설정의 초기 세팅을 작업합니다!

## 📄 To-Do
- [ ] exception 패키지 설정
- [ ] 공통 에러처리 프레임 만들기
- [ ] 응답 초기 설정 만들기
