### ISSUE TITLE
[♻️ refactor] [2차] 홈화면 > 딱 맞는 대학생 인턴 공고 : 데이터 형식 및 추가 변동사항 적용

### ISSUE THREAD

**Issue by junggyo1020** [teamterning/Terning-Server#97]
## ⚙️ ISSUE
- 기존에는 뷰가 유사하지만 데이터 형식을 다르게 전달된 부분들이 있어, 코드의 통일성과 유지보수성을 높이기 위해 전달되는 데이터의 형식을 최대한 통일하는 작업 진행
- 필터링 된 공고의 총 개수(totalCount)를 추가로 보내주도록 수정
- startYear, startMonth → startYearMonth로 변수 통합
- 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 internshipAnnouncementId로 통신하는 것으로 변경되었으므로 해당 API에서는 더 이상 scrapId가 아닌 isScrapped라는 필드로 스크랩 여부 전달

## 📄 To-Do
- [x] 필터링 된 공고의 총 개수(totalCount)를 추가로 보내주도록 수정
- [x] startYear, startMonth → startYearMonth로 변수 통합
- [x] 스크랩 추가 & 취소 & 색상 수정시 모두 기존 scrapId에서 internshipAnnouncementId로 통신하는 것으로 변경되었으므로 해당 API에서는 더 이상 scrapId가 아닌 isScrapped라는 필드로 스크랩여부 전달
